// AUTH MODULE
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const REMEMBER_PASSWORD = 'REMEMBER_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const CONFIRM_EMAIL = 'CONFIRM_EMAIL'
export const CONFIRM_USER_EMAIL = 'CONFIRM_USER_EMAIL'
export const WELCOME_EMAIL = 'WELCOME_EMAIL'

// USERS MODULE
export const FETCH_USERS = 'FETCH_USERS'
export const UPDATE_USER = 'UPDATE_USER'
export const SELECTED_USER = 'SELECTED_USER'
export const STORE_USER = 'STORE_USER'
export const DELETE_USER = 'DELETE_USER'
export const STORE_USER_PERSON = 'STORE_USER_PERSON'
export const DELETE_USER_PERSON = 'DELETE_USER_PERSON'

// JOBS MODULE
export const GET_JOBS = 'GET_JOBS'
export const STORE_JOB = 'STORE_JOB'
export const EDIT_JOB = 'EDIT_JOB'
export const DELETE_JOB = 'DELETE_JOB'

// TEACHERS (AND PENDING TEACHERS) MODULE
export const GET_PENDING_TEACHERS = 'GET_PENDING_TEACHERS'
export const REMOVE_PENDING_TEACHER = 'REMOVE_PENDING_TEACHER'
export const GET_TEACHERS = 'GET_TEACHERS'

// GOOGLE USERS MODULE
export const FETCH_GOOGLE_USERS = 'FETCH_GOOGLE_USERS'
export const STORE_GOOGLE_USER = 'STORE_GOOGLE_USER'

// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'

// CONFIRM DIALOG
export const SET_CONFIRM_DIALOG_SHOW = 'SET_CONFIRM_DIALOG_SHOW'
export const CONFIRM_DIALOG = 'CONFIRM_DIALOG'

// INCIDENTS
export const SET_INCIDENTS = 'SET_INCIDENTS'
export const ADD_INCIDENT = 'ADD_INCIDENT'
export const CLOSE_INCIDENT = 'CLOSE_INCIDENT'
export const OPEN_INCIDENT = 'OPEN_INCIDENT'
export const DELETE_INCIDENT = 'DELETE_INCIDENT'
export const UPDATE_INCIDENT = 'UPDATE_INCIDENT'

// STUDIES
export const SET_STUDIES = 'SET_STUDIES'
export const ADD_STUDY = 'ADD_STUDY'
export const DELETE_STUDY = 'DELETE_STUDY'

// SUBJECTS
export const SET_SUBJECTS = 'SET_SUBJECTS'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'

// SUBJECT_GROUPS
export const SET_SUBJECT_GROUPS = 'SET_SUBJECT_GROUPS'
export const ADD_SUBJECT_GROUP = 'ADD_SUBJECT_GROUP'
export const DELETE_SUBJECT_GROUP = 'DELETE_SUBJECT_GROUP'

// COURSES
export const SET_COURSES = 'SET_COURSES'

// FAMILIES
export const SET_FAMILIES = 'SET_FAMILIES'

// DEPARTMENTS
export const SET_DEPARTMENTS = 'SET_DEPARTMENTS'

// DEPARTMENTS
export const SET_POSITIONS = 'SET_POSITIONS'
