// AUTH
export const LOGGED = 'LOGGED'
export const USER = 'USER'

// SNACKBAR
export const SET_SNACKBAR_SHOW = 'SET_SNACKBAR_SHOW'
export const SET_SNACKBAR_COLOR = 'SET_SNACKBAR_COLOR'
export const SET_SNACKBAR_TEXT = 'SET_SNACKBAR_TEXT'
export const SET_SNACKBAR_SUBTEXT = 'SET_SNACKBAR_SUBTEXT'
export const SET_SNACKBAR_TIMEOUT = 'SET_SNACKBAR_TIMEOUT'

// CONFIRM DIALOG
export const SET_CONFIRM_DIALOG_SHOW = 'SET_CONFIRM_DIALOG_SHOW'

// USERS
export const SELECTED_USER = 'SELECTED_USER'
export const SET_USERS = 'SET_USERS'
export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const EDIT_USER = 'EDIT_USER'

// JOBS
export const SET_JOBS = 'SET_JOBS'
export const ADD_JOB = 'ADD_JOB'
export const DELETE_JOB = 'DELETE_JOB'

// TEACHERS
export const SET_PENDING_TEACHERS = 'SET_PENDING_TEACHERS'
export const SET_TEACHERS = 'SET_TEACHERS'
export const REMOVE_PENDING_TEACHER = 'REMOVE_PENDING_TEACHER'
export const DELETE_TEACHER = 'DELETE_TEACHER'

// GOOGLE USERS
export const SET_GOOGLE_USERS = 'SET_GOOGLE_USERS'
export const ADD_GOOGLE_USER = 'ADD_GOOGLE_USER'
export const DELETE_GOOGLE_USER = 'DELETE_GOOGLE_USER'

// INCIDENTS
export const SET_INCIDENTS = 'SET_INCIDENTS'
export const ADD_INCIDENT = 'ADD_INCIDENT'
export const CLOSE_INCIDENT = 'CLOSE_INCIDENT'
export const OPEN_INCIDENT = 'OPEN_INCIDENT'
export const DELETE_INCIDENT = 'DELETE_INCIDENT'
export const UPDATE_INCIDENT = 'UPDATE_INCIDENT'

// STUDIES
export const SET_STUDIES = 'SET_STUDIES'
export const ADD_STUDY = 'ADD_STUDY'
export const DELETE_STUDY = 'DELETE_STUDY'

// STUDIES
export const SET_SUBJECTS = 'SET_SUBJECTS'
export const ADD_SUBJECT = 'ADD_SUBJECT'
export const DELETE_SUBJECT = 'DELETE_SUBJECT'
